server {
    listen 80;
    server_name _;

    location = / {
        return 302 /resume/;
    }

    location /resume/ {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /resume/index.html;
    }
}
